In [1]:
#installing numpy
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
#importing numpy
import numpy as np

In [3]:
data=np.random.rand(2,3,4)
zeroes=np.zeros((2,2,2))
full=np.full((2,2,2),7)
ones=np.ones((2,2,2))

In [4]:
data

array([[[0.58547499, 0.69104897, 0.75975403, 0.65755705],
        [0.15574634, 0.54659   , 0.85999787, 0.96910229],
        [0.69332913, 0.41450351, 0.19293299, 0.05346763]],

       [[0.96287015, 0.15125066, 0.9476299 , 0.15237276],
        [0.09498275, 0.36396301, 0.13696141, 0.49041229],
        [0.42038233, 0.60866877, 0.98865479, 0.50676816]]])

In [5]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [6]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [7]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [8]:
arr=np.array(((1,2,3,4),(1,2,3,4)))

In [9]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [10]:
type(arr)

numpy.ndarray

In [12]:
#attributes
shape=data.shape
size=data.size
types=data.dtype

In [13]:
shape

(2, 3, 4)

In [14]:
size

24

In [15]:
types

dtype('float64')

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("iris.csv")

In [3]:
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
#converting pandas to numpy
array=df.to_numpy()

In [5]:
array

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

In [9]:
import numpy as np

In [10]:
dataset=np.array(array)

In [11]:
print(dataset[1])

[4.9 3.0 1.4 0.2 'Iris-setosa']


In [15]:
#accesing single value in two dimension array
print(dataset[1][1])

3.0


In [16]:
#shaping in nupy
print(dataset.shape)

(150, 5)


In [41]:
#reshaping an array
#dataset=dataset.reshape(4:5)
#print(array(dataset))

In [20]:
#splitting array
new=np.array_split(dataset,3)

In [21]:
print(new)

[array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Ir

In [25]:
#shaping each split
num=new[2]
print(num.shape)

(50, 5)


In [27]:
print(dataset.dtype)

object


In [32]:
bit=new[2][2][0]
bit

7.1

In [40]:
unsplitted=dataset[2][2]
print(unsplitted)

1.3


In [42]:
#slicing
print(dataset[1:5])

[[4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']]
